const nameData = {

japan:{
male:[
{roman:"minato", native:"湊"},
{roman:"iori", native:"伊織"},
{roman:"yuito", native:"結翔"},
{roman:"rui", native:"琉生"},
{roman:"ren", native:"蓮"},
{roman:"saku", native:"朔"},
{roman:"aoi", native:"碧"},
{roman:"hinata", native:"陽向"},
{roman:"haruto", native:"陽翔"},
{roman:"ran", native:"藍"},
{roman:"yamato", native:"大和"},
{roman:"asahi", native:"朝陽"},
{roman:"sora", native:"蒼空"},
{roman:"haruto", native:"晴"},
{roman:"hiroto", native:"大翔"},
{roman:"haru", native:"暖"},
{roman:"nagi", native:"凪"},
{roman:"minato", native:"湊斗"},
{roman:"jin", native:"仁"},
{roman:"akari", native:"陽"},
{roman:"ritu", native:"律"},
{roman:"souma", native:"颯真"},
{roman:"sou", native:"想"},
{roman:"yuma", native:"悠真"},
{roman:"sora", native:"空"},
{roman:"souma", native:"蒼真"},
{roman:"aoto", native:"蒼大"},
{roman:"youta", native:"陽太"},
{roman:"hayate", native:"颯"},
{roman:"ibuki", native:"一颯"},
{roman:"sui", native:"翠"},
{roman:"taisei", native:"大晴"},
{roman:"yuto", native:"陽斗"},
{roman:"rituki", native:"律希"},
{roman:"souta", native:"颯太"},
{roman:"tihaya", native:"千颯"},
{roman:"kanato", native:"奏翔"},
{roman:"ryuto", native:"琉翔"},
{roman:"ituki", native:"樹"},
{roman:"sena", native:"世凪"},
{roman:"aoi", native:"蒼"},
{roman:"syu", native:"柊"},
{roman:"haruto", native:"遥斗"},
{roman:"kai", native:"櫂"},
{roman:"aoi", native:"葵"},
{roman:"kaio", native:"海斗"},
{roman:"kanato", native:"叶翔"},
{roman:"arata", native:"新"},
{roman:"aoto", native:"蒼翔"},
{roman:"taiyou", native:"太陽"},
{roman:"kaede", native:"楓"},
{roman:"kazuma", native:"楓真"},
{roman:"aoto", native:"碧杜"},
{roman:"minato", native:"湊音"},
{roman:"haruto", native:"悠翔"},
{roman:"kohaku", native:"琥珀"},
{roman:"gaku", native:"岳"},
{roman:"satoshi", native:"慧"},
{roman:"yuito", native:"結斗"},
{roman:"chihaya", native:"千隼"},
{roman:"you", native:"優"},
{roman:"haruhi", native:"悠陽"},
{roman:"youta", native:"陽大"},
{roman:"ryuto", native:"琉斗"},
{roman:"hibiki", native:"響"},
{roman:"zen", native:"善"},
{roman:"sota", native:"奏太"},
{roman:"sora", native:"想空"},
{roman:"sota", native:"想太"},
{roman:"yuito", native:"唯斗"},
{roman:"you", native:"悠"},
{roman:"hinata", native:"陽奏"},
{roman:"riku", native:"理玖"},
{roman:"rihito", native:"理仁"},
{roman:"rei", native:"玲"},
{roman:"shoukuu", native:"翔空"},
{roman:"aito", native:"愛翔"},
{roman:"asahi", native:"旭"},
{roman:"io", native:"一桜"},
{roman:"kaoru", native:"薫"},
{roman:"yuito", native:"結仁"},
{roman:"hikaru", native:"光"},
{roman:"syu", native:"周"},
{roman:"haruto", native:"晴斗"},
{roman:"haruto", native:"晴翔"},
{roman:"zen", native:"然"},
{roman:"zen", native:"禅"},
{roman:"aoto", native:"碧斗"},
{roman:"yuto", native:"悠人"},
{roman:"yuji", native:"悠仁"},

{roman:"yuusei", native:"悠晴"},
{roman:"hayato", native:"颯斗"},
{roman:"kento", native:"絢翔"},
{roman:"kanata", native:"夏向"},
{roman:"kaito", native:"海翔"},
{roman:"kouki", native:"光希"},
{roman:"mizuki", native:"瑞己"},
{roman:"haruki", native:"晴琉"},
{roman:"souta", native:"奏多"},
{roman:"souta", native:"奏汰"}

],
female:[
{roman:"midori", native:"翠"},
{roman:"himari", native:"陽葵"},
{roman:"tumugi", native:"紬"},
{roman:"mashiro", native:"茉白"},
{roman:"rin", native:"凛"},
{roman:"hana", native:"陽菜"},
{roman:"koharu", native:"心陽"},
{roman:"iroha", native:"彩葉"},
{roman:"uta", native:"詩"},
{roman:"kotoha", native:"琴葉"},
{roman:"yuna", native:"結菜"},
{roman:"aoi", native:"葵"},
{roman:"emma", native:"咲茉"},
{roman:"sana", native:"紗菜"},
{roman:"nagisa", native:"凪咲"},
{roman:"noa", native:"乃愛"},
{roman:"emma", native:"依茉"},
{roman:"mei", native:"芽生"},
{roman:"oto", native:"桜都"},
{roman:"mio", native:"澪"},
{roman:"sakura", native:"咲良"},
{roman:"tumugi", native:"紬希"},
{roman:"miyu", native:"美桜"},
{roman:"mei", native:"芽依"},
{roman:"yui", native:"結愛"},
{roman:"iroha", native:"彩羽"},
{roman:"nagi", native:"凪"},
{roman:"yuzuki", native:"結月"},
{roman:"momoka", native:"百花"},
{roman:"ran", native:"藍"},
{roman:"ann", native:"杏"},
{roman:"yuzuha", native:"柚葉"},
{roman:"riko", native:"莉子"},
{roman:"hana", native:"華"},
{roman:"itoha", native:"絃葉"},
{roman:"sizuku", native:"雫"},
{roman:"haruto", native:"晴"},
{roman:"rin", native:"凜"},
{roman:"yui", native:"結衣"},
{roman:"ran", native:"蘭"},
{roman:"suzuha", native:"涼葉"},
{roman:"ithika", native:"一華"},
{roman:"oto", native:"桜叶"},
{roman:"koharu", native:"心春"},
{roman:"tumugi", native:"紬葵"},
{roman:"honoka", native:"帆花"},
{roman:"rio", native:"莉央"},
{roman:"ema", native:"愛茉"},
{roman:"otoha", native:"音羽"},
{roman:"nagisa", native:"凪紗"},
{roman:"mituki", native:"美月"},
{roman:"fuka", native:"風花"},
{roman:"yuzuki", native:"柚希"},
{roman:"yuzuki", native:"柚月"},
{roman:"maturi", native:"茉莉"},
{roman:"suzu", native:"すず"},
{roman:"emma", native:"永茉"},
{roman:"mei", native:"芽郁"},
{roman:"koto", native:"琴"},
{roman:"natuki", native:"菜月"},
{roman:"sana", native:"咲奈"},
{roman:"sana", native:"紗凪"},
{roman:"mio", native:"心音"},
{roman:"yui", native:"心結"},
{roman:"koharu", native:"心晴"},
{roman:"noa", native:"望愛"},
{roman:"hiro", native:"陽彩"},
{roman:"sakura", native:"さくら"},
{roman:"airi", native:"愛莉"},
{roman:"akane", native:"茜"},
{roman:"ito", native:"依采"},
{roman:"natume", native:"夏芽"},
{roman:"kanon", native:"花音"},
{roman:"kanoa", native:"叶愛"},
{roman:"hana", native:"椛"},
{roman:"kotone", native:"琴音"},
{roman:"yui", native:"結羽"},
{roman:"ito", native:"絃"},
{roman:"koto", native:"瑚都"},
{roman:"hikari", native:"光"},
{roman:"sana", native:"咲那"},
{roman:"sakura", native:"桜"},
{roman:"shino", native:"詩乃"},
{roman:"nanase", native:"七瀬"},
{roman:"sana", native:"紗奈"},
{roman:"sana", native:"紗那"},
{roman:"koto", native:"心都"},
{roman:"miyu", native:"美結"},
{roman:"kaede", native:"楓"},
{roman:"aoi", native:"碧"},
{roman:"ichka", native:"唯花"},
{roman:"yuno", native:"唯乃"},
{roman:"hiyori", native:"陽依"},
{roman:"hinano", native:"陽菜乃"},
{roman:"rituka", native:"律花"},
{roman:"nodoka", native:"和花"},
{roman:"rio", native:"莉緒"},
{roman:"akari", native:"あかり"},
{roman:"emma", native:"えま"},
{roman:"anna", native:"杏奈"}

]
},

usa:{
male:[
"liam",
"noah",
"oliver",
"elijah",
"james"
],
female:[
"olivia",
"emma",
"ava",
"sophia",
"isabella"
]
},

korea:{
male:[
{roman:"minjun", native:"민준"},
{roman:"seojun", native:"서준"},
{roman:"jiho", native:"지호"},
{roman:"yujun", native:"유준"},
{roman:"junseo", native:"준서"}
],
female:[
{roman:"seo-yeon", native:"서연"},
{roman:"jiwoo", native:"지우"},
{roman:"ha-rin", native:"하린"},
{roman:"minseo", native:"민서"},
{roman:"yuna", native:"유나"}
]
}

}

const flags = {
japan:"🇯🇵",
usa:"🇺🇸",
korea:"🇰🇷"
}

const countryNames = {
japan:"Japan",
usa:"USA",
korea:"Korea"
}
