const nameData = {

japan:{
male:[
{roman:"minato", native:"湊"},
{roman:"iori", native:"伊織"},
{roman:"yuito", native:"結翔"},
{roman:"rui", native:"琉生"},
{roman:"ren", native:"蓮"},
{roman:"saku", native:"朔"},
{roman:"aoi", native:"碧"},
{roman:"hinata", native:"陽向"},
{roman:"haruto", native:"陽翔"},
{roman:"ran", native:"藍"},
{roman:"yamato", native:"大和"},
{roman:"asahi", native:"朝陽"},
{roman:"sora", native:"蒼空"},
{roman:"haruto", native:"晴"},
{roman:"hiroto", native:"大翔"},
{roman:"haru", native:"暖"},
{roman:"nagi", native:"凪"},
{roman:"minato", native:"湊斗"},
{roman:"jin", native:"仁"},
{roman:"akari", native:"陽"},
{roman:"ritu", native:"律"},
{roman:"souma", native:"颯真"},
{roman:"sou", native:"想"},
{roman:"yuma", native:"悠真"},
{roman:"sora", native:"空"},
{roman:"souma", native:"蒼真"},
{roman:"aoto", native:"蒼大"},
{roman:"youta", native:"陽太"},
{roman:"hayate", native:"颯"},
{roman:"ibuki", native:"一颯"},
{roman:"sui", native:"翠"},
{roman:"taisei", native:"大晴"},
{roman:"yuto", native:"陽斗"},
{roman:"rituki", native:"律希"},
{roman:"souta", native:"颯太"},
{roman:"tihaya", native:"千颯"},
{roman:"kanato", native:"奏翔"},
{roman:"ryuto", native:"琉翔"},
{roman:"ituki", native:"樹"},
{roman:"sena", native:"世凪"},
{roman:"aoi", native:"蒼"},
{roman:"syu", native:"柊"},
{roman:"haruto", native:"遥斗"},
{roman:"kai", native:"櫂"},
{roman:"aoi", native:"葵"},
{roman:"kaio", native:"海斗"},
{roman:"kanato", native:"叶翔"},
{roman:"arata", native:"新"},
{roman:"aoto", native:"蒼翔"},
{roman:"taiyou", native:"太陽"},
{roman:"kaede", native:"楓"},
{roman:"kazuma", native:"楓真"},
{roman:"aoto", native:"碧杜"},
{roman:"minato", native:"湊音"},
{roman:"haruto", native:"悠翔"},
{roman:"kohaku", native:"琥珀"},
{roman:"gaku", native:"岳"},
{roman:"satoshi", native:"慧"},
{roman:"yuito", native:"結斗"},
{roman:"chihaya", native:"千隼"},
{roman:"you", native:"優"},
{roman:"haruhi", native:"悠陽"},
{roman:"youta", native:"陽大"},
{roman:"ryuto", native:"琉斗"},
{roman:"hibiki", native:"響"},
{roman:"zen", native:"善"},
{roman:"sota", native:"奏太"},
{roman:"sora", native:"想空"},
{roman:"sota", native:"想太"},
{roman:"yuito", native:"唯斗"},
{roman:"you", native:"悠"},
{roman:"hinata", native:"陽奏"},
{roman:"riku", native:"理玖"},
{roman:"rihito", native:"理仁"},
{roman:"rei", native:"玲"},
{roman:"shoukuu", native:"翔空"},
{roman:"aito", native:"愛翔"},
{roman:"asahi", native:"旭"},
{roman:"io", native:"一桜"},
{roman:"kaoru", native:"薫"},
{roman:"yuito", native:"結仁"},
{roman:"hikaru", native:"光"},
{roman:"syu", native:"周"},
{roman:"haruto", native:"晴斗"},
{roman:"haruto", native:"晴翔"},
{roman:"zen", native:"然"},
{roman:"zen", native:"禅"},
{roman:"aoto", native:"碧斗"},
{roman:"yuto", native:"悠人"},
{roman:"yuji", native:"悠仁"},
{roman:"yuusei", native:"悠晴"},
{roman:"hayato", native:"颯斗"},
{roman:"kento", native:"絢翔"},
{roman:"kanata", native:"夏向"},
{roman:"kaito", native:"海翔"},
{roman:"kouki", native:"光希"},
{roman:"mizuki", native:"瑞己"},
{roman:"haruki", native:"晴琉"},
{roman:"souta", native:"奏多"},
{roman:"souta", native:"奏汰"}

],
female:[
{roman:"midori", native:"翠"},
{roman:"himari", native:"陽葵"},
{roman:"tumugi", native:"紬"},
{roman:"mashiro", native:"茉白"},
{roman:"rin", native:"凛"},
{roman:"hana", native:"陽菜"},
{roman:"koharu", native:"心陽"},
{roman:"iroha", native:"彩葉"},
{roman:"uta", native:"詩"},
{roman:"kotoha", native:"琴葉"},
{roman:"yuna", native:"結菜"},
{roman:"aoi", native:"葵"},
{roman:"emma", native:"咲茉"},
{roman:"sana", native:"紗菜"},
{roman:"nagisa", native:"凪咲"},
{roman:"noa", native:"乃愛"},
{roman:"emma", native:"依茉"},
{roman:"mei", native:"芽生"},
{roman:"oto", native:"桜都"},
{roman:"mio", native:"澪"},
{roman:"sakura", native:"咲良"},
{roman:"tumugi", native:"紬希"},
{roman:"miyu", native:"美桜"},
{roman:"mei", native:"芽依"},
{roman:"yui", native:"結愛"},
{roman:"iroha", native:"彩羽"},
{roman:"nagi", native:"凪"},
{roman:"yuzuki", native:"結月"},
{roman:"momoka", native:"百花"},
{roman:"ran", native:"藍"},
{roman:"ann", native:"杏"},
{roman:"yuzuha", native:"柚葉"},
{roman:"riko", native:"莉子"},
{roman:"hana", native:"華"},
{roman:"itoha", native:"絃葉"},
{roman:"sizuku", native:"雫"},
{roman:"haruto", native:"晴"},
{roman:"rin", native:"凜"},
{roman:"yui", native:"結衣"},
{roman:"ran", native:"蘭"},
{roman:"suzuha", native:"涼葉"},
{roman:"ithika", native:"一華"},
{roman:"oto", native:"桜叶"},
{roman:"koharu", native:"心春"},
{roman:"tumugi", native:"紬葵"},
{roman:"honoka", native:"帆花"},
{roman:"rio", native:"莉央"},
{roman:"ema", native:"愛茉"},
{roman:"otoha", native:"音羽"},
{roman:"nagisa", native:"凪紗"},
{roman:"mituki", native:"美月"},
{roman:"fuka", native:"風花"},
{roman:"yuzuki", native:"柚希"},
{roman:"yuzuki", native:"柚月"},
{roman:"maturi", native:"茉莉"},
{roman:"suzu", native:"すず"},
{roman:"emma", native:"永茉"},
{roman:"mei", native:"芽郁"},
{roman:"koto", native:"琴"},
{roman:"natuki", native:"菜月"},
{roman:"sana", native:"咲奈"},
{roman:"sana", native:"紗凪"},
{roman:"mio", native:"心音"},
{roman:"yui", native:"心結"},
{roman:"koharu", native:"心晴"},
{roman:"noa", native:"望愛"},
{roman:"hiro", native:"陽彩"},
{roman:"sakura", native:"さくら"},
{roman:"airi", native:"愛莉"},
{roman:"akane", native:"茜"},
{roman:"ito", native:"依采"},
{roman:"natume", native:"夏芽"},
{roman:"kanon", native:"花音"},
{roman:"kanoa", native:"叶愛"},
{roman:"hana", native:"椛"},
{roman:"kotone", native:"琴音"},
{roman:"yui", native:"結羽"},
{roman:"ito", native:"絃"},
{roman:"koto", native:"瑚都"},
{roman:"hikari", native:"光"},
{roman:"sana", native:"咲那"},
{roman:"sakura", native:"桜"},
{roman:"shino", native:"詩乃"},
{roman:"nanase", native:"七瀬"},
{roman:"sana", native:"紗奈"},
{roman:"sana", native:"紗那"},
{roman:"koto", native:"心都"},
{roman:"miyu", native:"美結"},
{roman:"kaede", native:"楓"},
{roman:"aoi", native:"碧"},
{roman:"ichka", native:"唯花"},
{roman:"yuno", native:"唯乃"},
{roman:"hiyori", native:"陽依"},
{roman:"hinano", native:"陽菜乃"},
{roman:"rituka", native:"律花"},
{roman:"nodoka", native:"和花"},
{roman:"rio", native:"莉緒"},
{roman:"akari", native:"あかり"},
{roman:"emma", native:"えま"},
{roman:"anna", native:"杏奈"}

]
},

usa:{
male:[
"Noah",
"Liam",
"Oliver",
"Elijah",
"Mateo",
"Levi",
"Lucas",
"Ezra",
"Asher",
"Luca",
"Leo",
"James",
"Henry",
"Hudson",
"Elias",
"Michael",
"Theodore",
"Samuel",
"Muhammad",
"Theo",
"Benjamin",
"Grayson",
"Daniel",
"Sebastian",
"Ethan",
"Jack",
"Josiah",
"Mason",
"Maverick",
"Gabriel",
"Waylon",
"Wyatt",
"Carter",
"Isaiah",
"William",
"Alexander",
"David",
"Owen",
"Julian",
"Santiago",
"Jackson",
"Luke",
"Cooper",
"Adam",
"Matthew",
"Logan",
"Ezekiel",
"Caleb",
"Roman",
"Kai",
"John",
"Aiden",
"Weston",
"Miles",
"Lincoln",
"Atlas",
"Rowan",
"Silas",
"Nolan",
"Enzo",
"Jayden",
"Anthony",
"Thomas",
"Joseph",
"Nathan",
"Amir",
"Jacob",
"Bennett",
"Isaac",
"Wesley",
"Charlie",
"Beau",
"Eli",
"Joshua",
"Colton",
"Micah",
"Jeremiah",
"Zion",
"Everett",
"Adrian",
"Myles",
"Ryan",
"Adriel",
"Xavier",
"Luka",
"Cameron",
"Andrew",
"Christian",
"Jace",
"River",
"Malachi",
"Jaxon",
"Walker",
"Christopher",
"Arthur",
"Ali",
"Brooks",
"Nathaniel",
"Parker",
"Easton"
],

female:[
"Olivia",
"Amelia",
"Sophia",
"Emma",
"Isabella",
"Charlotte",
"Eliana",
"Ellie",
"Aurora",
"Mia",
"Ava",
"Lily",
"Luna",
"Evelyn",
"Violet",
"Aria",
"Sofia",
"Hazel",
"Harper",
"Layla",
"Nova",
"Willow",
"Ivy",
"Gianna",
"Eleanor",
"Ella",
"Scarlett",
"Elizabeth",
"Chloe",
"Elena",
"Nora",
"Penelope",
"Lainey",
"Isla",
"Camila",
"Avery",
"Riley",
"Mila",
"Delilah",
"Lucy",
"Valentina",
"Leilani",
"Grace",
"Paisley",
"Naomi",
"Abigail",
"Emilia",
"Iris",
"Ayla",
"Stella",
"Emily",
"Maya",
"Amara",
"Zoe",
"Eden",
"Josie",
"Autumn",
"Hannah",
"Zoey",
"Alice",
"Athena",
"Victoria",
"Millie",
"Sophie",
"Kinsley",
"Sadie",
"Aaliyah",
"Ruby",
"Adeline",
"Daisy",
"Melody",
"Clara",
"Emery",
"Raelynn",
"Eloise",
"Serenity",
"Madison",
"Maria",
"Liliana",
"Leah",
"Bella",
"Addison",
"Lyla",
"Sarah",
"Gabriella",
"Madelyn",
"Brooklyn",
"Everly",
"Emersyn",
"Brielle",
"Hailey",
"Sienna",
"Charlie",
"Lillian",
"Catalina",
"Josephine",
"Juniper",
"Oaklynn",
"Vivian",
"Kehlani"
]
},

korea:{
male:[
{roman:"Doyun", native:"도윤"},
{roman:"Ijun", native:"이준"},
{roman:"Hajun", native:"하준"},
{roman:"Siu", native:"시우"},
{roman:"Dohyeon", native:"도현"},
{roman:"Seojun", native:"서준"},
{roman:"Seonu", native:"선우"},
{roman:"Ian", native:"이안"},
{roman:"Tae-o", native:"태오"},
{roman:"Eunu", native:"은우"},
{roman:"Doha", native:"도하"},
{roman:"Suho", native:"수호"},
{roman:"Ihyeon", native:"이현"},
{roman:"Uju", native:"우주"},
{roman:"Jiho", native:"지호"},
{roman:"Yujun", native:"유준"},
{roman:"Eunho", native:"은호"},
{roman:"Yunu", native:"윤우"},
{roman:"Siyun", native:"시윤"},
{roman:"Juwon", native:"주원"},
{roman:"Yeonu", native:"연우"},
{roman:"Ujin", native:"우진"},
{roman:"Yejun", native:"예준"},
{roman:"Jihan", native:"지한"},
{roman:"Ido", native:"이도"},
{roman:"Hajin", native:"하진"},
{roman:"Dojun", native:"도준"},
{roman:"Ihan", native:"이한"},
{roman:"Junu", native:"준우"},
{roman:"Jihu", native:"지후"},
{roman:"Minjun", native:"민준"},
{roman:"Roun", native:"로운"},
{roman:"Yuchan", native:"유찬"},
{roman:"Ideun", native:"이든"},
{roman:"Yuan", native:"유안"},
{roman:"Taei", native:"태이"},
{roman:"Taeha", native:"태하"},
{roman:"Jiu", native:"지우"},
{roman:"Hyeonu", native:"현우"},
{roman:"Geonu", native:"건우"},
{roman:"Sion", native:"시온"},
{roman:"Sian", native:"시안"},
{roman:"Doyeong", native:"도영"},
{roman:"Haon", native:"하온"},
{roman:"Seou", native:"서우"},
{roman:"Seojin", native:"서진"},
{roman:"Jeong-u", native:"정우"},
{roman:"Yunjae", native:"윤재"},
{roman:"Junseo", native:"준서"},
{roman:"Taeyun", native:"태윤"},
{roman:"Hamin", native:"하민"},
{roman:"Yul", native:"율"},
{roman:"Jaeha", native:"재하"},
{roman:"Jian", native:"지안"},
{roman:"Daon", native:"다온"},
{roman:"Ichan", native:"이찬"},
{roman:"Sihyeon", native:"시현"},
{roman:"Yuhyeon", native:"유현"},
{roman:"Seonho", native:"선호"},
{roman:"Seoho", native:"서호"},
{roman:"Jihun", native:"지훈"},
{roman:"Doyul", native:"도율"},
{roman:"Yunho", native:"윤호"},
{roman:"Jaei", native:"재이"},
{roman:"Ijin", native:"이진"},
{roman:"Jio", native:"지오"},
{roman:"Jinu", native:"진우"},
{roman:"Juan", native:"주안"},
{roman:"Ubin", native:"우빈"},
{roman:"Dowon", native:"도원"},
{roman:"Yugeon", native:"유건"},
{roman:"Jaeyun", native:"재윤"},
{roman:"Ajun", native:"아준"},
{roman:"Dojin", native:"도진"},
{roman:"Yun", native:"윤"},
{roman:"Sihu", native:"시후"},
{roman:"Danu", native:"단우"},
{roman:"Hayul", native:"하율"},
{roman:"Roi", native:"로이"},
{roman:"Dogyeom", native:"도겸"},
{roman:"Siwon", native:"시원"},
{roman:"Han-gyeol", native:"한결"},
{roman:"Yeonjun", native:"연준"},
{roman:"Haru", native:"하루"},
{roman:"Eunchan", native:"은찬"},
{roman:"Jun", native:"준"},
{roman:"Siho", native:"시호"},
{roman:"Ujae", native:"우재"},
{roman:"Doun", native:"도운"},
{roman:"Ijae", native:"이재"},
{roman:"Raon", native:"라온"},
{roman:"Juho", native:"주호"},
{roman:"Haneul", native:"하늘"},
{roman:"Hyeon", native:"현"},
{roman:"Jion", native:"지온"},
{roman:"Haram", native:"하람"},
{roman:"Idam", native:"이담"},
{roman:"Jimin", native:"지민"},
{roman:"Haseong", native:"하성"},
{roman:"Jiyul", native:"지율"}

],
female:[
{roman:"Seoa", native:"서아"},
{roman:"Seoyun", native:"서윤"},
{roman:"Iseo", native:"이서"},
{roman:"Harin", native:"하린"},
{roman:"Hayun", native:"하윤"},
{roman:"Arin", native:"아린"},
{roman:"Jian", native:"지안"},
{roman:"Ayun", native:"아윤"},
{roman:"Jiyu", native:"지유"},
{roman:"Sia", native:"시아"},
{roman:"Yunseo", native:"윤서"},
{roman:"Jia", native:"지아"},
{roman:"Jiu", native:"지우"},
{roman:"Chaei", native:"채이"},
{roman:"Doa", native:"도아"},
{roman:"Yuna", native:"유나"},
{roman:"Sua", native:"수아"},
{roman:"Chae-a", native:"채아"},
{roman:"Isol", native:"이솔"},
{roman:"Yerin", native:"예린"},
{roman:"Seoha", native:"서하"},
{roman:"Yuha", native:"유하"},
{roman:"Yunseul", native:"윤슬"},
{roman:"Yuju", native:"유주"},
{roman:"Jaei", native:"재이"},
{roman:"Ina", native:"이나"},
{roman:"Soi", native:"소이"},
{roman:"Na-eun", native:"나은"},
{roman:"Seoyeon", native:"서연"},
{roman:"Chaewon", native:"채원"},
{roman:"Yena", native:"예나"},
{roman:"Chaeyun", native:"채윤"},
{roman:"Ihyeon", native:"이현"},
{roman:"Yeseo", native:"예서"},
{roman:"Ria", native:"리아"},
{roman:"Chae-eun", native:"채은"},
{roman:"Ha-eun", native:"하은"},
{roman:"Roa", native:"로아"},
{roman:"Se-a", native:"세아"},
{roman:"Taeri", native:"태리"},
{roman:"Yuna", native:"윤아"},
{roman:"Sieun", native:"시은"},
{roman:"Seoyul", native:"서율"},
{roman:"Soyun", native:"소윤"},
{roman:"Yeonseo", native:"연서"},
{roman:"Eunchae", native:"은채"},
{roman:"Ahyeon", native:"아현"},
{roman:"Dain", native:"다인"},
{roman:"Seohyeon", native:"서현"},
{roman:"Seou", native:"서우"},
{roman:"Yeonu", native:"연우"},
{roman:"Eunseo", native:"은서"},
{roman:"Chaerin", native:"채린"},
{roman:"Dayun", native:"다윤"},
{roman:"Seoeun", native:"서은"},
{roman:"Hari", native:"하리"},
{roman:"Seora", native:"설아"},
{roman:"Haerin", native:"해린"},
{roman:"Jua", native:"주아"},
{roman:"Yui", native:"유이"},
{roman:"Nayun", native:"나윤"},
{roman:"Haena", native:"해나"},
{roman:"Ain", native:"아인"},
{roman:"Soyul", native:"소율"},
{roman:"Jiyun", native:"지윤"},
{roman:"Yujin", native:"유진"},
{roman:"Hayeon", native:"하연"},
{roman:"Minseo", native:"민서"},
{roman:"Da-eun", native:"다은"},
{roman:"Bom", native:"봄"},
{roman:"Yueun", native:"유은"},
{roman:"Sol", native:"솔"},
{roman:"Ian", native:"이안"},
{roman:"Jiyul", native:"지율"},
{roman:"Daon", native:"다온"},
{roman:"Rua", native:"루아"},
{roman:"Soeun", native:"소은"},
{roman:"Haein", native:"해인"},
{roman:"Haru", native:"하루"},
{roman:"Taei", native:"태이"},
{roman:"Taerin", native:"태린"},
{roman:"Saebom", native:"새봄"},
{roman:"Seol", native:"설"},
{roman:"Ye-eun", native:"예은"},
{roman:"Eunha", native:"은하"},
{roman:"Sarang", native:"사랑"},
{roman:"Eunyu", native:"은유"},
{roman:"Yuan", native:"유안"},
{roman:"Dana", native:"단아"},
{roman:"Hana", native:"하나"},
{roman:"Sian", native:"시안"},
{roman:"Jei", native:"제이"},
{roman:"Doeun", native:"도은"},
{roman:"Jimin", native:"지민"},
{roman:"Ijin", native:"이진"},
{roman:"Jiwon", native:"지원"},
{roman:"Jion", native:"지온"},
{roman:"Yewon", native:"예원"},
{roman:"Narin", native:"나린"}

],

france:{
male:[
{roman:"Gabriel", native:"Gabriel"},
{roman:"Alexandre", native:"Alexandre"},
{roman:"Arthur", native:"Arthur"},
{roman:"Adam", native:"Adam"},
{roman:"Raphael", native:"Raphaël"},
{roman:"Louis", native:"Louis"},
{roman:"Paul", native:"Paul"},
{roman:"Antoine", native:"Antoine"},
{roman:"Maxime", native:"Maxime"},
{roman:"Thomas", native:"Thomas"},
{roman:"Victor", native:"Victor"},
{roman:"Lucas", native:"Lucas"},
{roman:"Jules", native:"Jules"},
{roman:"Nathan", native:"Nathan"},
{roman:"Hugo", native:"Hugo"},
{roman:"Sacha", native:"Sacha"},
{roman:"Mohamed", native:"Mohamed"},
{roman:"Enzo", native:"Enzo"},
{roman:"Gaspard", native:"Gaspard"},
{roman:"Clement", native:"Clément"},
{roman:"Samuel", native:"Samuel"},
{roman:"Ethan", native:"Ethan"},
{roman:"Leo", native:"Leo"},
{roman:"Adrien", native:"Adrien"},
{roman:"Martin", native:"Martin"},
{roman:"Rayan", native:"Rayan"},
{roman:"Baptiste", native:"Baptiste"},
{roman:"Yanis", native:"Yanis"},
{roman:"Simon", native:"Simon"},
{roman:"Joseph", native:"Joseph"},
{roman:"Mathis", native:"Mathis"},
{roman:"Oscar", native:"Oscar"},
{roman:"Alexis", native:"Alexis"},
{roman:"Pierre", native:"Pierre"},
{roman:"Noah", native:"Noah"},
{roman:"Axel", native:"Axel"},
{roman:"Theo", native:"Theo"},
{roman:"Romain", native:"Romain"},
{roman:"Valentin", native:"Valentin"},
{roman:"Augustin", native:"Augustin"},
{roman:"Julien", native:"Julien"},
{roman:"Nicolas", native:"Nicolas"},
{roman:"Maxence", native:"Maxence"},
{roman:"Noe", native:"Noé"},
{roman:"Benjamin", native:"Benjamin"},
{roman:"Quentin", native:"Quentin"},
{roman:"Tom", native:"Tom"},
{roman:"Charles", native:"Charles"},
{roman:"David", native:"David"},
{roman:"Jean", native:"Jean"},
{roman:"Eliott", native:"Eliott"},
{roman:"Aaron", native:"Aaron"},
{roman:"Elias", native:"Elias"},
{roman:"Matthieu", native:"Matthieu"},
{roman:"Tristan", native:"Tristan"},
{roman:"Timothee", native:"Timothée"},
{roman:"Mathieu", native:"Mathieu"},
{roman:"Matteo", native:"Matteo"},
{roman:"William", native:"William"},
{roman:"Amine", native:"Amine"},
{roman:"Felix", native:"Félix"},
{roman:"Come", native:"Côme"},
{roman:"Ruben", native:"Ruben"},
{roman:"Ulysse", native:"Ulysse"},
{roman:"Antonin", native:"Antonin"},
{roman:"Guillaume", native:"Guillaume"},
{roman:"Aurelien", native:"Aurélien"},
{roman:"Robin", native:"Robin"},
{roman:"Mael", native:"Maël"},
{roman:"Kevin", native:"Kévin"},
{roman:"Mehdi", native:"Mehdi"},
{roman:"Ismael", native:"Ismaël"},
{roman:"Liam", native:"Liam"},
{roman:"Gabin", native:"Gabin"},
{roman:"Noam", native:"Noam"},
{roman:"Evan", native:"Evan"},
{roman:"Marius", native:"Marius"},
{roman:"Mathias", native:"Mathias"},
{roman:"Isaac", native:"Isaac"},
{roman:"Samy", native:"Samy"},
{roman:"Ibrahim", native:"Ibrahim"},
{roman:"Basile", native:"Basile"},
{roman:"Daniel", native:"Daniel"},
{roman:"Emile", native:"Emile"},
{roman:"Lucien", native:"Lucien"},
{roman:"Elie", native:"Elie"},
{roman:"Rayane", native:"Rayane"},
{roman:"Leonard", native:"Léonard"},
{roman:"Thibault", native:"Thibault"},
{roman:"Achille", native:"Achille"},
{roman:"Leon", native:"Léon"},
{roman:"Edouard", native:"Edouard"},
{roman:"Hadrien", native:"Hadrien"},
{roman:"Lenny", native:"Lenny"},
{roman:"Matheo", native:"Matheo"},
{roman:"Malo", native:"Malo"},
{roman:"Titouan", native:"Titouan"},
{roman:"Solal", native:"Solal"},
{roman:"Joshua", native:"Joshua"},
{roman:"Max", native:"Max"}
],

female:[
{roman:"Louise", native:"Louise"},
{roman:"Camille", native:"Camille"},
{roman:"Emma", native:"Emma"},
{roman:"Ines", native:"Inès"},
{roman:"Chloe", native:"Chloé"},
{roman:"Sarah", native:"Sarah"},
{roman:"Alice", native:"Alice"},
{roman:"Lea", native:"Léa"},
{roman:"Juliette", native:"Juliette"},
{roman:"Jeanne", native:"Jeanne"},
{roman:"Eva", native:"Eva"},
{roman:"Clara", native:"Clara"},
{roman:"Lina", native:"Lina"},
{roman:"Anna", native:"Anna"},
{roman:"Charlotte", native:"Charlotte"},
{roman:"Mathilde", native:"Mathilde"},
{roman:"Marie", native:"Marie"},
{roman:"Manon", native:"Manon"},
{roman:"Lucie", native:"Lucie"},
{roman:"Anais", native:"Anaïs"},
{roman:"Jade", native:"Jade"},
{roman:"Zoe", native:"Zoé"},
{roman:"Nina", native:"Nina"},
{roman:"Lou", native:"Lou"},
{roman:"Clemence", native:"Clémence"},
{roman:"Pauline", native:"Pauline"},
{roman:"Lisa", native:"Lisa"},
{roman:"Adele", native:"Adèle"},
{roman:"Gabrielle", native:"Gabrielle"},
{roman:"Romane", native:"Romane"},
{roman:"Julia", native:"Julia"},
{roman:"Victoria", native:"Victoria"},
{roman:"Emilie", native:"Emilie"},
{roman:"Rose", native:"Rose"},
{roman:"Julie", native:"Julie"},
{roman:"Margaux", native:"Margaux"},
{roman:"Lena", native:"Léna"},
{roman:"Victoire", native:"Victoire"},
{roman:"Lola", native:"Lola"},
{roman:"Valentine", native:"Valentine"},
{roman:"Agathe", native:"Agathe"},
{roman:"Alix", native:"Alix"},
{roman:"Elisa", native:"Elisa"},
{roman:"Elise", native:"Elise"},
{roman:"Margot", native:"Margot"},
{roman:"Yasmine", native:"Yasmine"},
{roman:"Laura", native:"Laura"},
{roman:"Noa", native:"Noa"},
{roman:"Sofia", native:"Sofia"},
{roman:"Noemie", native:"Noémie"},
{roman:"Heloise", native:"Héloïse"},
{roman:"Sara", native:"Sara"},
{roman:"Apolline", native:"Apolline"},
{roman:"Salome", native:"Salomé"},
{roman:"Diane", native:"Diane"},
{roman:"Maya", native:"Maya"},
{roman:"Ambre", native:"Ambre"},
{roman:"Elsa", native:"Elsa"},
{roman:"Josephine", native:"Joséphine"},
{roman:"Capucine", native:"Capucine"},
{roman:"Ava", native:"Ava"},
{roman:"Sasha", native:"Sasha"},
{roman:"Eleonore", native:"Eléonore"},
{roman:"Iris", native:"Iris"},
{roman:"Fatoumata", native:"Fatoumata"},
{roman:"Alicia", native:"Alicia"},
{roman:"Eden", native:"Eden"},
{roman:"Mila", native:"Mila"},
{roman:"Nour", native:"Nour"},
{roman:"Andrea", native:"Andrea"},
{roman:"Garance", native:"Garance"},
{roman:"Aya", native:"Aya"},
{roman:"Violette", native:"Violette"},
{roman:"Constance", native:"Constance"},
{roman:"Justine", native:"Justine"},
{roman:"Melissa", native:"Melissa"},
{roman:"Oceane", native:"Océane"},
{roman:"Olivia", native:"Olivia"},
{roman:"Esther", native:"Esther"},
{roman:"Ines", native:"Inès"},
{roman:"Luna", native:"Luna"},
{roman:"Suzanne", native:"Suzanne"},
{roman:"Mariam", native:"Mariam"},
{roman:"Maelys", native:"Maëlys"},
{roman:"Myriam", native:"Myriam"},
{roman:"Sophie", native:"Sophie"},
{roman:"Celia", native:"Célia"},
{roman:"Lila", native:"Lila"},
{roman:"Madeleine", native:"Madeleine"},
{roman:"Marion", native:"Marion"},
{roman:"Anouk", native:"Anouk"},
{roman:"Stella", native:"Stella"},
{roman:"Eloise", native:"Eloïse"},
{roman:"Charlie", native:"Charlie"},
{roman:"Leonie", native:"Léonie"},
{roman:"Chiara", native:"Chiara"},
{roman:"Carla", native:"Carla"},
{roman:"Blanche", native:"Blanche"},
{roman:"Faustine", native:"Faustine"},
{roman:"Claire", native:"Claire"}
]
  
}
  
}

const flags = {
japan:"🇯🇵",
usa:"🇺🇸",
korea:"🇰🇷",
france:"🇫🇷"
}

const countryNames = {
japan:"Japan",
usa:"USA",
korea:"Korea",
france:"France"
}
